# Generated by Django 3.0.6 on 2020-06-26 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_kategorije', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Jelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_jela', models.CharField(max_length=200)),
                ('broj_kalorija', models.IntegerField(default=0)),
                ('kategorija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calorie.Kategorija')),
            ],
        ),
    ]
